### ISSUE TITLE
A file is missing

### ISSUE THREAD

**Issue by CuloArdido** [axilmar/lottery#1]
When I try to compile the Test program the PredictionAlgorithmA.cpp file is missing and according to [this](https://github.com/axilmar/lottery/blob/90ab47e1a91651d110f9fd8902ac8ef5ffc566ce/projects/Test/Lottery.vcxproj#L49) it's in your Google Drive folder. Could you upload that file to the repository or tell me how to compile without it?

**Comment by axilmar** [comment]
Thanks for the attention to this little library, but there is no
PredictionAlgorithmA.cpp actually: PredictionAlgorithmA is just the name I
gave to the class I use for testing various methods of predictions (of
which none so far have come up with any success better than random).

**Comment by CuloArdido** [comment]
The reason that I opened this issue is because I can't compile the file projects/Test/mail.cpp in Linux. I tried with the following command:
```
g++ -g -std=c++14 -I ../../source main.cpp ../../source/Game.cpp ../../source/CSVFile.cpp ../../source/RandomPredictionAlgorithm.cpp ../../source/log.cpp
```
But the following appears:
```
/tmp/ccSHrPMN.o: In function `std::_MakeUniq<Lottery::PredictionAlgorithmA>::__single_object std::make_unique<Lottery::PredictionAlgorithmA, Lottery::Game&>(Lottery::Game&)':
/usr/lib/gcc/i686-pc-linux-gnu/7.3.0/include/g++-v7/bits/unique_ptr.h:825: undefined reference to `Lottery::PredictionAlgorithmA::PredictionAlgorithmA(Lottery::Game const&)'
collect2: error: ld returned 1 exit status
```
Also try adding all the files that are in Lottery.vcxproj and the same error appears before along with similar ones. Any idea why that is?
Sorry I took so long to respond, I am usually busy with other things and I have not paid much attention to this.

**Comment by axilmar** [comment]
The file is missing on purpose. You are supposed to write your own
prediction algorithm.

**Comment by axilmar** [comment]
The library is intentionally incomplete. Whoever finds a lottery prediction algorithm that produces better results against random selection that are viable for playing, please do notify me and I will incorporate the algorithm into the library (aside from using it to get rich, of course :-)).
